# Generated by Django 3.1.2 on 2020-10-13 12:35

from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('particular', models.CharField(max_length=255)),
                ('cost_unit_price', models.FloatField()),
                ('selling_unit_price', models.FloatField()),
                ('bought_for', models.CharField(choices=[('INPUT', 'Input'), ('OUTPUT', 'Output'), ('BOTH', 'Both')], default='OUTPUT', max_length=50, verbose_name='Purpose')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('sub_total', models.FloatField()),
                ('discount_percent', utils.fields.PercentField(verbose_name='Discount Percent')),
                ('net_total', models.FloatField()),
                ('customer', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], default='CASH', max_length=50, verbose_name='Status')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeteria.particular')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('total_price', models.FloatField()),
                ('bought_by', models.CharField(max_length=255)),
                ('bought_from', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], default='CASH', max_length=50, verbose_name='Status')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeteria.particular')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
