# Generated by Django 3.1.2 on 2020-10-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_expenditure',
            field=models.BooleanField(default=False, help_text="Click on checkbox for general expenditure and don't click for investment", verbose_name='Is Expenditure or not ?'),
        ),
    ]
